apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-onscreen
  namespace: widget-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-onscreen
  template:
    metadata:
      labels:
        app: wp-onscreen
        logging: enabled
    spec:
      containers:
      - image: "||registry||/widget-platform/onscreen:||version||"
        name: wp-onscreen
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: qp-config
        env:
        - name: ConfigurationService__Url
          valueFrom:
            configMapKeyRef:
              name: qp-config
              key: CONFIGURATION_SERVICE_HOST
        - name: ConfigurationService__Token
          valueFrom:
            configMapKeyRef:
              name: qp-config
              key: CONFIGURATION_SERVICE_TOKEN
        - name: QpAuthSettings__WorkAsAdministrator
          value: 'true'
        volumeMounts:
          - name: time-config
            mountPath: /etc/localtime
            subPathExpr: $(TZ)
          - name: timezone-config
            mountPath: /etc/timezone
            subPath: TZ
        resources:
          limits:
            memory: "256Mi"
      volumes:
        - name: time-config
          hostPath:
            path: /usr/share/zoneinfo
        - name: timezone-config
          configMap: 
            name: qp-config
            items:
            - key: TZ
              path: TZ
---
apiVersion: v1
kind: Service
metadata:
  name: wp-onscreen
  namespace: widget-platform
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wp-onscreen
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,X-QP8-Access-Token,Customer-Code"
  name: wp-onscreen
  namespace: widget-platform
spec:
  rules:
  - host: "||host||"
    http:
      paths:
      - backend:
          serviceName: wp-onscreen
          servicePort: 80
