// tree
export const TOGGLE_COMPONENT = 'TOGGLE_COMPONENT';

export const EXPAND_SUBTREE = 'EXPAND_SUBTREE';
export const COLLAPSE_SUBTREE = 'COLLAPSE_SUBTREE';

export const OPEN_FULL_SUBTREE = 'TOGGLE_FULL_SUBTREE';
// export const LOADED_COMPONENT_TREE = 'LOADED_COMPONENT_TREE';
export const CHANGE_COMPONENT_TREE_SEARCH_TEXT = 'CHANGE_COMPONENT_TREE_SEARCH_TEXT';
export const UPDATE_COMPONENTS = 'UPDATE_COMPONENTS';
export const TOGGLE_SHOW_ONLY_WIDGETS = 'TOGGLE_SHOW_ONLY_WIDGETS';
export const TOGGLE_COMPONENT_TREE_SEARCH_BOX = 'TOGGLE_COMPONENT_TREE_SEARCH_BOX';


export const COMPONENTS_LIST_UPDATE_REQUESTED = 'COMPONENTS_LIST_UPDATE_REQUESTED';
export const COMPONENTS_LIST_UPDATED = 'COMPONENTS_LIST_UPDATED';


export const TREE_DATA_UPDATE_REQUESTED = 'TREE_DATA_UPDATE_REQUESTED';
export const UPDATE_TREE_DATA = 'UPDATE_TREE_DATA';
export const TREE_DATA_UPDATED = 'TREE_DATA_UPDATED';


export const COMPONENT_TREE_ONSCREEN_SELECT_COMPONENT = {
  SELECT_COMPONENT: 'ONSCREEN_SELECT_COMPONENT/SELECT_COMPONENT',
  OPEN_FULL_SUBTREE: 'ONSCREEN_SELECT_COMPONENT/OPEN_FULL_SUBTREE',
  SCROLL_TO_TREE_ITEM: 'ONSCREEN_SELECT_COMPONENT/SCROLL_TO_TREE_ITEM',
};

export const DRAG_AND_DROP = {
  DRAG_START: 'DRAG_AND_DROP/START',
  DRAG_END: 'DRAG_AND_DROP/END',
};
