// tree
export const TOGGLE_COMPONENT = 'TOGGLE_COMPONENT';
export const TOGGLE_SUBTREE = 'TOGGLE_SUBTREE';
export const TOGGLE_FULL_SUBTREE = 'TOGGLE_FULL_SUBTREE';
// export const LOADED_COMPONENT_TREE = 'LOADED_COMPONENT_TREE';
export const CHANGE_COMPONENT_TREE_SEARCH_TEXT = 'CHANGE_COMPONENT_TREE_SEARCH_TEXT';
export const UPDATE_COMPONENTS = 'UPDATE_COMPONENTS';
export const TOGGLE_SHOW_ONLY_WIDGETS = 'TOGGLE_SHOW_ONLY_WIDGETS';
export const TOGGLE_COMPONENT_TREE_SEARCH_BOX = 'TOGGLE_COMPONENT_TREE_SEARCH_BOX';


export const COMPONENTS_LIST_UPDATE_REQUESTED = 'COMPONENTS_LIST_UPDATE_REQUESTED';
export const COMPONENTS_LIST_UPDATED = 'COMPONENTS_LIST_UPDATED';
