export const CONFIRMATION_DIALOG_SHOW = 'CONFIRMATION_DIALOG_SHOW';
export const CONFIRMATION_DIALOG_CONFIRMED = 'CONFIRMATION_DIALOG_CONFIRMED';
export const CONFIRMATION_DIALOG_CANCELLED = 'CONFIRMATION_DIALOG_CANCELLED';
